{{- if (.Values.gatewayHost) }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-secrets-prereq
  namespace: {{ .Values.istio.namespace }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-secrets-for-gateway-secrets-creation
  namespace: {{ .Values.istio.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create

---  

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-prereq-to-secrets
  namespace: {{ .Values.istio.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-secrets-for-gateway-secrets-creation
subjects:
- kind: ServiceAccount
  name: istio-secrets-prereq
  namespace: {{ .Values.istio.namespace }}

---  

apiVersion: batch/v1
kind: Job
metadata:
  name: istio-secrets-prereq
  namespace: {{ .Values.istio.namespace }}
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: istio-secrets-prereq
    spec:
      serviceAccountName: istio-secrets-prereq
      containers:
      - name: secret-init
        image: axway-docker-public-registry.bintray.io/kubectl
        env:
        - name: GATEWAY_DNS
          value: {{ .Values.gatewayHost }}
        - name: GATEWAY_SECRET_NAME
          value: {{ template "gatewayCertName" . }}  
        command:
        - sh
        - -c
        - |
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/ca-selfsigned.key -out /tmp/ca-selfsigned.crt -subj "/C=US/ST=Phoenix/L=Phoenix/O=Global Security/OU=Axway RD/CN=$GATEWAY_DNS"
          kubectl create secret tls $GATEWAY_SECRET_NAME --cert /tmp/ca-selfsigned.crt --key /tmp/ca-selfsigned.key -o yaml

      restartPolicy: Never
---
{{- end }}
